### ISSUE TITLE
章节代码 样例限制异常 

### ISSUE THREAD

**Issue by HbnKing** [whaleal/mongodb-manual-zh#126]
https://docs.whaleal.com/mongodb-manual-zh/01-introduction/05-bson-types/01-bson-type-comparison-order.html

<img width="932" alt="image" src="https://github.com/whaleal/mongodb-manual-zh/assets/22213280/b0325fec-fc52-46f2-a168-43440d6e628d">

**Comment by hanpengs** [comment]
已修改
